**TASK:** import numpy

In [27]:
import numpy as np

**TASK:** define vector 'x' with three coordinates

In [28]:
x = np.array([1, 2, 3])

**TASK:** define (2 x 2) matrix 'A' 


In [29]:
A = np.array([[1,2], [3,4]])

**TASK:** define (2 x 2) matrix 'B'

In [30]:
B = np.array([[5,6], [7,8]])

**TASK:** check the type of 'x'

In [31]:
type(x)

numpy.ndarray

**TASK:** check the type of 'A'

In [32]:
type(A)

numpy.ndarray

**TASK:**  check the shape of 'x'


In [33]:
x.shape

(3,)

**TASK:** check the type of 'A'

In [34]:
A.shape

(2, 2)

**TASK:** 

In [35]:
"""
Define function 'have_same_shape' which checks if two arrays have same shape.

PARAMS:
    array_1 (numpy.ndarray) - first array
    array_2 (numpy.ndarray) - second array
RETURN:
    True - if arrays have same shape
    False - if arrays do not have same shape

Also print 'Arrays must have same shape!' when returning False
"""

"\nDefine function 'have_same_shape' which checks if two arrays have same shape.\n\nPARAMS:\n    array_1 (numpy.ndarray) - first array\n    array_2 (numpy.ndarray) - second array\nRETURN:\n    True - if arrays have same shape\n    False - if arrays do not have same shape\n\nAlso print 'Arrays must have same shape!' when returning False\n"

In [36]:
def have_same_shape(array_1, array_2):
    if array_1.shape == array_2.shape:
        return True
    else:
        print('Arrays must have same shape!')
        return False

**TASK:** call the function 'have_same_shape' with matrix 'A' and vector 'x' as inputs

In [37]:
have_same_shape(A,x)

Arrays must have same shape!


False

**TASK:**  call the function 'have_same_shape' with matrix 'A' and matrix 'B' as inputs

In [38]:
have_same_shape(A, B)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_addition' which perform matrix addition value by value.

PARAMS:
    A (numpy.ndarray) - first array
    B (numpy.ndarray) - second array
RETURN:
    C (numpy.ndarray) - new A+B array

In this task do not consider broadcasting.
Do not forget to check arrays shapes (you can use 'have_same_shape' function defined before)

"""


In [75]:
def matrix_addition(A, B):
    if have_same_shape(A, B) == True:
        C = np.zeros(A.shape)
        for i in range(len(A)):
            for j in range(len(A[0])):
                C[i][j] = A[i][j] + B[i][j]
        return C
    else:
        print('Matrices not the same size. Cannot add.')
        

**TASK:** call the function 'matrix_addition' with matrix 'A' and matrix 'B' as inputs

In [76]:
matrix_addition(A, B)

array([[ 6.,  8.],
       [10., 12.]])

**TASK:** 

In [47]:
"""
Define 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition

PARAMS:
   lst_of_arr (list) - list of numpy.ndarrays
RETURN:
    NEW_ARRAY (numpy.ndarray) - new array

Use 'matrix_addition' function defined before.
"""

"\nDefine 'multiple_matrix_adition' function that takes list of arrays as the input and perform array addition\n\nPARAMS:\n   lst_of_arr (list) - list of numpy.ndarrays\nRETURN:\n    NEW_ARRAY (numpy.ndarray) - new array\n\nUse 'matrix_addition' function defined before.\n"

In [77]:
def multiple_matrix_addition(lst_of_arr):
    NEW_ARRAY = np.zeros(lst_of_arr[0].shape)
    for i in range(len(lst_of_arr)):
            NEW_ARRAY = matrix_addition(lst_of_arr[i], NEW_ARRAY)
    return NEW_ARRAY

In [78]:
C = np.array([[1,2],[3,4],[5,6]])

**TASK:** call the function 'multiple_matrix_addition' with matrix [A,A,B,B,B] as input


In [80]:
multiple_matrix_addition([A,A,B,B,B])

array([[17., 22.],
       [27., 32.]])

**TASK:** 

In [81]:
"""
Define function 'can_multiply' that checks if two arrays (matrices) can be multiplied

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    True - if arrays can be multiplied, also print the shape of the new array
    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'
    
"""

"\nDefine function 'can_multiply' that checks if two arrays (matrices) can be multiplied\n\nPARAMS:\n   array_a (numpy.ndarray) - first array\n   array_b (numpy.ndarray) - second array\nRETURN:\n    True - if arrays can be multiplied, also print the shape of the new array\n    False - if arrays can not be multiplied, also print 'Matrices can not be multiplied.'\n    \n"

In [84]:
def can_multiply(array_a, array_b):
    a_x, a_y = array_a.shape
    b_x, b_y = array_b.shape
    
    if a_y == b_x:
        return True
    else:
        return False

**TASK:** call the function 'can_multiply' with matrix 'A' and 'B' as inputs

In [85]:
can_multiply(A, B)

True

**TASK:**  define matrix (3 x 2) matrix C

In [87]:
C = np.array([[1,2], [3,4], [5,6]])

**TASK:**  call the function 'can_multiply' with matrix 'A' and 'C' as inputs

In [88]:
can_multiply(A, C)

False

**TASK:**  call the function 'can_multiply' with matrix 'C' and 'A' as inputs (now C,A not A,C). Do you know why is the result different?

In [89]:
can_multiply(C, A)

True

**TASK:** 

In [ ]:
"""
Define function 'matrix_multiplication' that multiply two numpy.ndarrays

PARAMS:
   array_a (numpy.ndarray) - first array
   array_b (numpy.ndarray) - second array
RETURN:
    NEW_ARRAY (numpy.ndarray) - new A * B array
    
Do not forget to check if two matrices can be multiplied.

"""

In [ ]:
def matrix_multiplication(array_a, array_b):
    if can_multiply(array_a, array_b) == True:
        a_x, a_y = array_a.shape
        b_x, b_y = array_b.shape
        array_c = np.zeros((a_x, b_y))
        for i in range(a_x):
            for j in range(b_y):
                for k in range(a_y):
                    array_c[i][j] += array_a[i][k]*array_b[k][j]
        return array_c
    else:
        return 'Cannot multiply matrices'

**TASK:**  call the function 'matrix_multiplication' with matrix 'C' and 'B' 


In [106]:
matrix_multiplication(C, B)

array([[19., 22.],
       [43., 50.],
       [67., 78.]])

**TASK:** call the function 'matrix_multiplication' with matrix 'A' and 'C' 

In [111]:
matrix_multiplication(A, C)

'Cannot multiply matrices'