In [2]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [4]:
A = np.array([[1,2], [3,4], [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [5]:
type(x), type(A)

(numpy.ndarray, numpy.ndarray)

In [6]:
A.shape

(3, 2)

In [7]:
x.shape

(4,)

In [8]:
len(x)

4

In [9]:
len(A)

3

In [10]:
A_T = A.T # can use A.T or A.transpose()

In [11]:
print(A_T)

[[1 3 5]
 [2 4 6]]


In [12]:
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
A_T.shape

(2, 3)

In [15]:
B = np.array([[2,5], [7,4], [4,3]])
B

array([[2, 5],
       [7, 4],
       [4, 3]])

In [17]:
C = A + B
print(C)

[[ 3  7]
 [10  8]
 [ 9  9]]


In [18]:
D = 1 + A
print(D)

[[2 3]
 [4 5]
 [6 7]]


In [19]:
B = np.array([[2],[4]])
B

array([[2],
       [4]])

In [20]:
B.shape

(2, 1)

In [21]:
print(B)

[[2]
 [4]]


In [22]:
C = np.dot(A, B) # can also use A.dot(B)
print(C)

[[10]
 [22]
 [34]]


In [23]:
C.shape

(3, 1)

In [24]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
IA = I.dot(A)
IA

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [26]:
M = np.array([[1,2], [3,4]])
M

array([[1, 2],
       [3, 4]])

In [28]:
det_M = np.linalg.det(M) # determinants can only be computed for square matrices
print(det_M)

-2.0000000000000004


In [29]:
A = np.array([[3,0,2], [2,0,-2], [0,1,1]])
A

array([[ 3,  0,  2],
       [ 2,  0, -2],
       [ 0,  1,  1]])

In [30]:
A_inv = np.linalg.inv(A)
print(A_inv)

[[ 0.2  0.2  0. ]
 [-0.2  0.3  1. ]
 [ 0.2 -0.3 -0. ]]


In [33]:
result = A.dot(A_inv)
print(result)

[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]
