# NumPy exercises

We are going to practice NumPy skills and basic syntax. put here also some examples that were not in the tutorial on purpose. Try to use google and official NumPy documentation to solve these exercises.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [4]:
a = np.zeros(10)
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [5]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [282]:
a = np.arange(0, 20)
print(a)
b = np.flip(a)
print(b)
c = a[::-1]
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
[19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [283]:
a = np.random.randint(0,9, size=(3,3))
print(a)

b=np.arange(9).reshape(3,3)
print(b)

[[6 1 6]
 [2 5 4]
 [0 8 1]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [145]:
a = np.array([1,2,0,0,4,0])
np.nonzero(a) # returns indicies

(array([0, 1, 4]),)

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [287]:
a = np.random.rand(3,3,3)
print(a)

b = np.random.randint(1,20, size=(3,3,3))
print(b)

[[[0.44938393 0.78539909 0.26617106]
  [0.90921536 0.82429953 0.32174742]
  [0.64563458 0.14091037 0.27270199]]

 [[0.28660488 0.27035205 0.41076315]
  [0.69555995 0.75910634 0.03370718]
  [0.83876993 0.19395328 0.03658609]]

 [[0.3605923  0.38715888 0.80975562]
  [0.63240928 0.22574997 0.63869771]
  [0.04051387 0.38693984 0.96208851]]]
[[[ 9 11  5]
  [ 7  2  9]
  [13 11 15]]

 [[ 8 17 15]
  [15  7 17]
  [15  8  2]]

 [[ 6 10  8]
  [15  6 15]
  [14  1  4]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [296]:
a = np.random.random((10,10))
print(a)

a_min, a_max = np.min(a), np.max(a)
print('\n')
print('a_min: {}     a_max: {}'.format(a_min, a_max))

[[0.24551116 0.07813299 0.72632393 0.82432098 0.98134851 0.77780617
  0.93089967 0.78881121 0.45708205 0.09000527]
 [0.86574389 0.63033731 0.5378637  0.41487833 0.36926928 0.34876575
  0.33429912 0.35750426 0.26134848 0.84017759]
 [0.00683879 0.98124778 0.58306274 0.41172981 0.53489469 0.95464758
  0.85139649 0.03871946 0.0773803  0.88369532]
 [0.84623797 0.83542529 0.10277829 0.12394184 0.04323924 0.40505604
  0.35773072 0.49666222 0.49316912 0.57730422]
 [0.52823511 0.76005163 0.24527577 0.66087884 0.09958153 0.8863649
  0.42923485 0.2135085  0.64444537 0.11179282]
 [0.06524948 0.29690864 0.97106405 0.72676654 0.19945754 0.13696122
  0.77494863 0.23112128 0.8272961  0.13338261]
 [0.32125966 0.14923768 0.90147705 0.41562736 0.91151899 0.80605081
  0.8723431  0.67856759 0.53346224 0.44571355]
 [0.1311135  0.89462146 0.04098838 0.67302167 0.606673   0.98332291
  0.05629791 0.0055843  0.60265447 0.72098164]
 [0.55406535 0.54387958 0.80747496 0.2880316  0.90052165 0.89329721
  0.36851031 

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [34]:
a = np.random.rand(30)
print(a)

[0.3714507  0.21671613 0.23697714 0.63160748 0.99258232 0.93735355
 0.64549478 0.75929057 0.0608293  0.082939   0.33305277 0.93154922
 0.67268986 0.83771793 0.60883262 0.92143726 0.41810733 0.50746455
 0.85292928 0.67013718 0.1784703  0.46732067 0.99470579 0.10267509
 0.10208569 0.46953191 0.19227596 0.18976874 0.73936064 0.56073129]


In [35]:
np.mean(a)

0.5228695011690505

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [297]:
a = np.ones((3,3))
a[1,1]=0
print(a)

[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


In [302]:
a = np.ones((10,10))
print(a)
print('\n')
a[1:-1, 1:-1] = 0
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (fi lled with 0's) around an existing array? (★☆☆)

In [305]:
a = np.ones((10,10))
a = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [52]:
0 * np.nan

nan

In [53]:
np.nan == np.nan

False

In [54]:
np.inf > np.nan

False

In [55]:
np.nan - np.nan

nan

In [56]:
np.nan in set([np.nan])

True

In [307]:
0.3 == 3 * 0.1

False

In [310]:
3*0.1

0.30000000000000004

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [312]:
np.diag([1,2,3,4], -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [311]:
np.diag((np.arange(4)+1), -1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [315]:
n = 0
for i in range(6):
    for j in range(7):
        for k in range(8):
            n += 1
            if n==100:
                break
        if n==100:
            break
    if n==100:
        break
        
print(i, j, k)

1 5 3


In [320]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [321]:
a = np.random.rand(5,5)
print(a)
norm = np.linalg.norm(a)
normal_array = a/norm
print(normal_array)

[[0.10011907 0.86873876 0.92030849 0.31663185 0.04762314]
 [0.17288424 0.40210669 0.79929109 0.85806632 0.58189215]
 [0.65839077 0.51062092 0.90543419 0.2385254  0.32631012]
 [0.48651181 0.34950536 0.36622174 0.00959679 0.08356486]
 [0.84565073 0.88526197 0.82466131 0.11274521 0.54784209]]
[[0.03477551 0.30174904 0.31966135 0.10997939 0.01654149]
 [0.06004987 0.13966835 0.27762698 0.29804206 0.2021153 ]
 [0.22868645 0.17735985 0.31449489 0.08284978 0.11334105]
 [0.16898575 0.12139772 0.12720402 0.00333336 0.02902555]
 [0.29372961 0.30748824 0.28643911 0.03916109 0.19028831]]


In [323]:
a = np.random.rand(5,5)
print(a)
a_min, a_max = np.min(a), np.max(a)

a = (a - a_min)/(a_max - a_min)
print(a)

[[0.8977489  0.80016274 0.15727377 0.5419184  0.81654923]
 [0.08954879 0.07004843 0.00495404 0.33414926 0.0492161 ]
 [0.33448709 0.54940951 0.0957456  0.91223602 0.97286191]
 [0.19257299 0.29828859 0.90615461 0.14530724 0.09967985]
 [0.32181164 0.86635756 0.28562485 0.92111345 0.6226824 ]]
[[0.92239654 0.82157479 0.15737007 0.55476805 0.83850459]
 [0.08739958 0.06725267 0.         0.34011007 0.04572961]
 [0.34045911 0.56250754 0.09380186 0.93736399 1.        ]
 [0.19383968 0.3030604  0.93108095 0.14500677 0.09786656]
 [0.32736339 0.88996438 0.28997678 0.94653577 0.63820987]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [139]:
a = np.arange(11)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10]


In [140]:
np.negative(a, where=((a>3) & (a<8)))

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10])

In [141]:
b = np.random.randint(0,15, size=(1,15))
print(b)

[[ 5  0  7 14  7 10 10 12 10 11  8 10 14  6 12]]


In [142]:
np.negative(b,where=((b>3) & (b<8)))

array([[-5,  0, -7,  8, -7,  5, 11,  6,  7,  0,  2,  0,  9, -6, 12]])

#### 29. How to round away from zero a float array ? (★☆☆)

In [151]:
a = np.arange(-2.1, 2.1, 0.1)
print(a)

[-2.10000000e+00 -2.00000000e+00 -1.90000000e+00 -1.80000000e+00
 -1.70000000e+00 -1.60000000e+00 -1.50000000e+00 -1.40000000e+00
 -1.30000000e+00 -1.20000000e+00 -1.10000000e+00 -1.00000000e+00
 -9.00000000e-01 -8.00000000e-01 -7.00000000e-01 -6.00000000e-01
 -5.00000000e-01 -4.00000000e-01 -3.00000000e-01 -2.00000000e-01
 -1.00000000e-01  1.77635684e-15  1.00000000e-01  2.00000000e-01
  3.00000000e-01  4.00000000e-01  5.00000000e-01  6.00000000e-01
  7.00000000e-01  8.00000000e-01  9.00000000e-01  1.00000000e+00
  1.10000000e+00  1.20000000e+00  1.30000000e+00  1.40000000e+00
  1.50000000e+00  1.60000000e+00  1.70000000e+00  1.80000000e+00
  1.90000000e+00  2.00000000e+00]


In [155]:
b = np.around(a, decimals=1)
print(b)

[-2.1 -2.  -1.9 -1.8 -1.7 -1.6 -1.5 -1.4 -1.3 -1.2 -1.1 -1.  -0.9 -0.8
 -0.7 -0.6 -0.5 -0.4 -0.3 -0.2 -0.1  0.   0.1  0.2  0.3  0.4  0.5  0.6
  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4  1.5  1.6  1.7  1.8  1.9  2. ]


#### 30. How to find common values between two arrays? (★☆☆)

In [163]:
a=np.random.randint(1,20, size=(1,10))
b=np.random.randint(5,25, size=(1,10))
print(a)
print(b)
np.intersect1d(a,b)

[[16 16  6  4  9 16 15 14 13 11]]
[[23 24 15 21 14 21 21 21  5 11]]


array([11, 14, 15])

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [68]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-68-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

In [69]:
print(np.emath.sqrt(-1))

1j


In [70]:
print(np.sqrt(-1))

nan


<ipython-input-70-41a4088c2eb8>:1: RuntimeWarning: invalid value encountered in sqrt
  print(np.sqrt(-1))


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [324]:
arr = []
for i in range(10):
    arr.append(np.random.randint(100))
print(arr)    


[4, 99, 93, 62, 55, 78, 51, 9, 47, 26]


In [326]:
def generate():
    for i in range(10):
        yield i #yield keyword implies a generator function
    
a = np.fromiter(generate(), dtype=int, count = -1)
print(a)

[0 1 2 3 4 5 6 7 8 9]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [330]:
a = np.linspace(0,1,12,endpoint=True)
print(a)
print('\n')
a = a[1:-1] #-1 is non-inclusive
print(a)

[0.         0.09090909 0.18181818 0.27272727 0.36363636 0.45454545
 0.54545455 0.63636364 0.72727273 0.81818182 0.90909091 1.        ]


[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆)

In [331]:
a = np.random.randint(1,21, size=(1,10))
print(a)
b = np.sort(a)
print(b)

[[ 5 17 13 17  6 12 11 16 17 16]]
[[ 5  6 11 12 13 16 16 17 17 17]]


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [178]:
a = [1,3,4,5,6]
b = [1,3,2,4,5]

np.array_equal(a,b)

False

In [179]:
a = [1,3,4,5,6]
b = [1,3,4,5,6]

np.array_equal(a,b)

True

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [341]:
a = np.random.rand(10)
print(a)
print('\n')
a[a.argmax()]=0
print(a)

[0.61508985 0.76869181 0.18565293 0.46551815 0.25443174 0.30542255
 0.90946062 0.60444347 0.82305309 0.89382142]


[0.61508985 0.76869181 0.18565293 0.46551815 0.25443174 0.30542255
 0.         0.60444347 0.82305309 0.89382142]


In [343]:
a = np.random.random(10)
print(a)
max = np.max(a)
print('\n')
print('max: {}'.format(max))
print('\n')
a[np.where(a == np.max(a))]=0
print(a)

[0.91485702 0.87318703 0.02150543 0.29351929 0.23538293 0.04320783
 0.86507258 0.04153623 0.65019826 0.40585009]


max: 0.9148570243711727


[0.         0.87318703 0.02150543 0.29351929 0.23538293 0.04320783
 0.86507258 0.04153623 0.65019826 0.40585009]


In [348]:
a = np.random.randint(1,5, size=(1,5))
print(a)
print(type(a))

a = np.random.rand(5)
print(a)
print(type(a))

[[1 1 3 3 1]]
<class 'numpy.ndarray'>
[0.14021721 0.46240236 0.24720232 0.59478477 0.14129433]
<class 'numpy.ndarray'>


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [191]:
a = np.arange(100)
b = np.random.uniform(0,100)
print(a)
print(b)
index = (np.abs(a-b)).argmin() # argmin returns the index
print(index)
print(a[index])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
46.062078599564884
46
46


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [281]:
a = np.arange(10, dtype=np.float32)
print(a)
a = a.astype(np.int32, copy=False)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 59. How to sort an array by the nth column? (★★☆)

In [214]:
a = np.array([[11,22,33],[54,15,16],[7,8,89]])
print(a)

[[11 22 33]
 [54 15 16]
 [ 7  8 89]]


In [217]:
print(a[:,1].argsort()) # argsort returns indicies that sort an array
print(a[a[:,1].argsort()])

[2 1 0]
[[ 7  8 89]
 [54 15 16]
 [11 22 33]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [197]:
a = np.random.randint(0,3,(4,10))
print(a)
print((~a.any(axis=0)).any())

[[1 0 1 0 0 0 1 2 1 1]
 [2 0 1 1 2 2 1 2 1 1]
 [2 2 2 1 1 1 2 2 1 1]
 [1 2 2 0 1 0 0 2 0 0]]
False


#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [244]:
a = (np.arange(5) + 1)
print(a)
a = np.insert(a, 1, [0,0,0])
print(a)
a = np.insert(a, 5, [0,0,0])
print(a)
a = np.insert(a, 9, [0,0,0])
print(a)
a = np.insert(a, 13, [0,0,0])
print(a)

[1 2 3 4 5]
[1 0 0 0 2 3 4 5]
[1 0 0 0 2 0 0 0 3 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 5]
[1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


In [245]:
a = np.array([1,2,3,4,5])
nz = 3
b = np.zeros(len(a)+(len(a)-1)*nz)
print(b)
print(len(b))
b[::4] = a
print(b)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
17
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 72. How to swap two rows of an array? (★★★)

In [246]:
a = np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [247]:
a[[1,2],:] = a[[2,1],:]
print(a)

[[ 0  1  2]
 [ 6  7  8]
 [ 3  4  5]
 [ 9 10 11]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [252]:
# Negate a boolean

a = np.array([True, False, True, True, False])
print(a)
np.logical_not(a)

[ True False  True  True False]


array([False,  True, False, False,  True])

In [257]:
# Change sign of a float

a = np.random.uniform(-3,3,5)
print(a)
np.negative(a)


[-0.30114373 -2.84527103  1.55288882 -2.87055913  0.86387802]


array([ 0.30114373,  2.84527103, -1.55288882,  2.87055913, -0.86387802])

#### 83. How to find the most frequent value in an array?

In [260]:
a = np.random.randint(1,10,20)
print(a)
np.bincount(a).argmax()

[6 8 9 4 6 9 9 6 9 7 2 5 9 1 5 7 3 3 2 9]


9

#### 89. How to get the n largest values of an array (★★★)

In [275]:
a = np.arange(10)
print(a)
np.random.shuffle(a)
print(a)

n=2
a[np.argsort(a)] #argsort returns index
a[np.argsort(a)[-n:]]

[0 1 2 3 4 5 6 7 8 9]
[5 6 1 3 0 2 8 9 7 4]


array([8, 9])

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [276]:
x = np.array([[20, 20, 20, 0],
              [0, 20, 20, 20],
              [0, 20, 20, 20],
              [20, 20, 20, 0],
              [10, 20, 20,20]])

y = np.ascontiguousarray(x).view(np.dtype((np.void, x.dtype.itemsize * x.shape[1])))
_, idx = np.unique(y, return_index=True)

unique_result = x[idx]

print(unique_result)

[[ 0 20 20 20]
 [10 20 20 20]
 [20 20 20  0]]
